# Agentic Framework — Autonomous Workflow Engine
from __future__ import annotations

import json
import subprocess
from pathlib import Path


def build_claude_cmd(
    claude_command: str,
    project_root: Path,
    prompt: str,
    *,
    print_mode: bool = True,
) -> list[str]:
    """Build Claude CLI command with tier-appropriate permission flags.

    Checks for .claude/settings.json (generated by `ag auto init`):
    - _tier=1: --dangerously-skip-permissions (sandbox)
    - _tier=2: --settings <path> (scoped permissions)
    - _tier=3 or no settings: no permission flags (interactive, safest)

    Users must run `ag auto init` to configure permissions before using
    autonomous modes. Without it, spawned Claude runs interactively.
    """
    cmd = [claude_command]

    if print_mode:
        cmd.append("--print")

    # Permission mode from settings (generated by `ag auto init --tier N`)
    # Without settings, runs in interactive mode (safest default).
    settings_path = project_root / ".claude" / "settings.json"
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text())
            tier = settings.get("_tier")
            if tier == 1:
                cmd.append("--dangerously-skip-permissions")
            elif tier == 2:
                cmd.extend(["--settings", str(settings_path)])
            # tier 3 or missing: no permission flags (interactive)
        except (json.JSONDecodeError, OSError):
            pass  # fall through to interactive mode

    cmd.append(prompt)
    return cmd


def spawn_claude(
    claude_command: str,
    project_root: Path,
    prompt: str,
    *,
    print_mode: bool = True,
    timeout: int = 300,
) -> str:
    """Spawn a Claude CLI instance and return combined stdout+stderr.

    Uses tier-appropriate permissions based on .claude/settings.json.
    """
    cmd = build_claude_cmd(
        claude_command, project_root, prompt,
        print_mode=print_mode,
    )

    try:
        proc = subprocess.run(
            cmd,
            cwd=str(project_root),
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return proc.stdout + proc.stderr
    except FileNotFoundError:
        return "error: claude command not found"
    except subprocess.TimeoutExpired:
        return f"error: Claude timed out after {timeout}s"
    except Exception as e:
        return f"error: {e}"
