"use client";

import { useMemo, useState } from "react";
import { TodoItemRow } from "../components/TodoItemRow";
import type { TodoItem } from "../lib/todo";
import { addTodo, toggleTodo } from "../lib/todo";
import styles from "./page.module.css";

const initialTodos: TodoItem[] = [
  { id: "t1", text: "Read CONTEXT_PACK.md", done: true },
  { id: "t2", text: "Implement a small feature", done: false },
  { id: "t3", text: "Mark feature Accepted in spec/FEATURES.md", done: false }
];

export default function HomePage() {
  const [todos, setTodos] = useState<TodoItem[]>(initialTodos);
  const [newText, setNewText] = useState("");

  const remaining = useMemo(() => todos.filter((t) => !t.done).length, [todos]);

  return (
    <main className={styles.main}>
      <header className={styles.header}>
        <div>
          <h1 className={styles.title}>Todo Web App</h1>
          <p className={styles.subtitle}>
            Example project generated by the agentic framework. State is local-only for now.
          </p>
        </div>
        <div className={styles.badge}>
          <span className={styles.badgeLabel}>Remaining</span>
          <span className={styles.badgeValue}>{remaining}</span>
        </div>
      </header>

      <section className={styles.card}>
        <form
          className={styles.addForm}
          onSubmit={(e) => {
            e.preventDefault();
            setTodos((prev) => addTodo(prev, newText));
            setNewText("");
          }}
        >
          <label className={styles.label} htmlFor="todoText">
            Add a todo
          </label>
          <div className={styles.row}>
            <input
              id="todoText"
              className={styles.input}
              placeholder="e.g. write tests for toggle logic"
              value={newText}
              onChange={(e) => setNewText(e.target.value)}
            />
            <button className={styles.button} type="submit">
              Add
            </button>
          </div>
          <p className={styles.hint}>Tip: keep tasks small and test-backed.</p>
        </form>

        <div className={styles.list} role="list" aria-label="Todo list">
          {todos.map((t) => (
            <TodoItemRow
              key={t.id}
              todo={t}
              onToggle={() => setTodos((prev) => toggleTodo(prev, t.id))}
            />
          ))}
        </div>
      </section>
    </main>
  );
}


